### ISSUE TITLE
Tecla crashes on startup about 90% of the time on Galaxy Note

### ISSUE THREAD

**Issue by ijdoc** [KomodoOpenLab/TeclaAccess#126]
From a user report, more details to follow.

**Comment by oranje** [comment]
Crashing reported in Galaxy Note (1), a few times per week.

Tecla Access app (0.9-beta) now crashes on phone start-up almost every time the phone is turned on.

**Comment by ijdoc** [comment]
The trace:

```
java.lang.NullPointerException
at ca.idi.tekla.ime.KeyboardSwitcher.getKeyboard(KeyboardSwitcher.java:182)
at ca.idi.tekla.ime.KeyboardSwitcher.setKeyboardMode(KeyboardSwitcher.java:162)
at ca.idi.tekla.ime.KeyboardSwitcher.setKeyboardMode(KeyboardSwitcher.java:152)
at ca.idi.tekla.ime.KeyboardSwitcher.setKeyboardMode(KeyboardSwitcher.java:146)
at ca.idi.tekla.ime.TeclaIME.hideAltNavKeyboard(TeclaIME.java:2205)
at ca.idi.tekla.ime.TeclaIME.hideSoftIME(TeclaIME.java:2409)
at ca.idi.tekla.ime.TeclaIME.access$11(TeclaIME.java:2408)
at ca.idi.tekla.ime.TeclaIME$7.run(TeclaIME.java:2083)
at android.os.Handler.handleCallback(Handler.java:587)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:3691)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:670)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by ijdoc** [comment]
Seems to have been fixed on the last build at:
https://github.com/idrc/TeclaAccess/blob/develop/tags/TeclaAccess_versioncode27_hotfix126.apk
