### ISSUE TITLE
java.lang.IllegalArgumentException: contentIntent required error caused by notification

### ISSUE THREAD

**Issue by ijdoc** [KomodoOpenLab/TeclaAccess#214]
As described in:
http://stackoverflow.com/questions/3112008/android-java-lang-illegalargumentexception-contentintent-required-error-cause

**Comment by ijdoc** [comment]
java.lang.IllegalArgumentException: contentIntent required: pkg=ca.idi.tekla id=2131099651 notification=Notification(vibrate=null,sound=default,defaults=0x1)
at android.os.Parcel.readException(Parcel.java:1251)
at android.os.Parcel.readException(Parcel.java:1235)
at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:274)
at android.app.NotificationManager.notify(NotificationManager.java:110)
at android.app.NotificationManager.notify(NotificationManager.java:90)
at ca.idi.tecla.framework.TeclaShieldService.showNotification(TeclaShieldService.java:479)
at ca.idi.tecla.framework.TeclaShieldService.run(TeclaShieldService.java:227)
at java.lang.Thread.run(Thread.java:1096)

**Comment by ijdoc** [comment]
According to the accepted answer on stackoverflow,

you need to set the contentIntent for your notification.

in your case:

notification.contentIntent = notificationIntent;
otherwise you will get the message, that the contentIntent of the notification is null, because it's not set.

the docu is here: http://developer.android.com/reference/android/app/Notification.html#contentIntent

i have a little example here: http://united-coders.com/nico-heid/show-progressbar-in-notification-area-like-google-does-when-downloading-from-android

**Comment by ijdoc** [comment]
This issue should now be solved. Will prepare release within two hours. Will require testing by @oranje
